FPTBook/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Data;
using FPTBook.Models;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize("RequireAdmin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _context.Categories.Where(c => c.IsApprove == false).ToListAsync();
            return View(categories);
        }
        public async Task<IActionResult> Approve(string id)
        {
            var category = await _context.Categories.SingleOrDefaultAsync(c => c.Id == id);
            category.IsApprove = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(string id)
        {
            var category = await _context.Categories.SingleOrDefaultAsync(c => c.Id == id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

FPTBook/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Data;
using FPTBook.Models;
using Microsoft.AspNetCore.Identity;
using FPTBook.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize("RequireAdmin")]

    public class UsersController : Controller
    {
        private readonly RoleManager<RoleModel> _roleManager;
        private readonly UserManager<AppUserModel> _userManager;
        public UsersController(RoleManager<RoleModel> roleManager, UserManager<AppUserModel> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Admin/Users
        public async Task<IActionResult> Customers()
        {
            var role = await _roleManager.FindByNameAsync("Customer");
            var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);

            return View(usersInRole);
        }
        public async Task<IActionResult> StoreOwners()
        {
            var role = await _roleManager.FindByNameAsync("StoreOwner");
            var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);

            return View(usersInRole);
        }
        
        public  IActionResult CustomerResetPassword(string id)
        {

            var result = new ResetPasswordVM
            {
                Id = id,
            };
            return View(result);
        }
        public IActionResult StoreOwnerResetPassword(string id)
        {
            var result = new ResetPasswordVM
            {
                Id = id,
            };
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> CustomerResetPassword(ResetPasswordVM model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);

            var token = await _userManager.GeneratePasswordResetTokenAsync(user);
            var result = await _userManager.ResetPasswordAsync(user, token, model.Password);
            if (result.Succeeded)
            {
                TempData["SuccessAlert"] = "Changed";

            }
            else
            {
                TempData["FailAlert"] = "Password required 1 character and 1 uppercase";
            }

            return RedirectToAction(nameof(Customers));
        }

        [HttpPost]
        public async Task<IActionResult> StoreOwnerResetPassword(ResetPasswordVM model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);

            var token = await _userManager.GeneratePasswordResetTokenAsync(user);
            var result = await _userManager.ResetPasswordAsync(user, token, model.Password);
            if (result.Succeeded)
            {
                TempData["SuccessAlert"] = "Changed";

            }
            else
            {
                TempData["FailAlert"] = "Password required 1 character and 1 uppercase";
            }

            return RedirectToAction(nameof(StoreOwners));
        }
    }
}

FPTBook/Areas/Customer/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Data;
using FPTBook.Models;
using System.Security.Claims;
using FPTBook.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize("RequireCustomer")]

    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICartRepository _cartRepos;
        public CartsController(ICartRepository cartRepository, ApplicationDbContext context)
        {
            _context = context;
            _cartRepos = cartRepository;
        }

        // GET: Customer/Carts
        public async Task<IActionResult> Index()
        {
            var result = await _cartRepos.Carts();
       
            return View(result);
        }

        
         public async Task<IActionResult> QuantityUpdate(string id, int quantity)
         {

            await _cartRepos.UpdateCartQuantity(id, quantity);

            return RedirectToAction(nameof(Index));
         }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _cartRepos.RemoveCart(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> CheckOut()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var res = await _cartRepos.CheckOut(userId);
            TempData["SuccessAlert"] = res.Messsage;
            return RedirectToAction(nameof(Index));

        }

    }
}

FPTBook/Areas/Customer/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Data;
using FPTBook.Models;
using FPTBook.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize("RequireCustomer")]

    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IOrderRepository _orderRepository;


        public OrdersController(IOrderRepository orderRepository, ApplicationDbContext context)
        {
            _context = context;
            _orderRepository = orderRepository;
        }

        public async Task<IActionResult> Index()
        {
            var result =  await _orderRepository.Orders();
            return View(result);
        }

        public async Task<IActionResult> Orders(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var orderDetails = await _orderRepository.OrderDetails(id);

             
            if (orderDetails == null)
            {
                return NotFound();
            }

            return View(orderDetails);
        }

       
      
    }
}

FPTBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPTBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/vendor.css" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link media="screen" rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.css" />
    <link media="screen" rel="stylesheet" href='https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.css' />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.js"></script>
</head>
<body>
    <header>
        @if (TempData["AlertMessage"] != null)
        {
            <script>
                alert(' @TempData["AlertMessage"]');
            </script>
        }
        @if (TempData["FailAlert"] != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    swal("Good job!", '@TempData["FailAlert"]', "error");
                };
            </script>
        }
        @if (TempData["SuccessAlert"] != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    swal("Good job!", '@TempData["SuccessAlert"]', "success");
                };
            </script>
        }
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                                <a class="nav-link text-dark" href="#">FPTBook</a>
                         </li>
                        @if (User.IsInRole("Admin")){

                             <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Users" asp-action="Customers">Customers</a>
                            </li>
                              <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Users" asp-action="StoreOwners">Store Owners</a>
                             </li>
                        }
                        @if (User.IsInRole("StoreOwner"))
                        {

                              <li class="nav-item">
                                <a class="nav-link" style="color:#777" asp-area="StoreOwner" asp-controller="Categories" asp-action="Index">Category</a>
                             </li>
                              <li class="nav-item">
                                <a class="nav-link" style="color:#777" asp-area="StoreOwner" asp-controller="Orders" asp-action="Index">OrderRecord</a>
                             </li>
                            
                            <li class="nav-item">
                                <a class="nav-link" style="color:#777" asp-area="StoreOwner" asp-controller="Books" asp-action="Index">Store</a>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="color:#777" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color:#777" asp-area="Customer" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color:#777" asp-area="Customer" asp-controller="Carts" asp-action="Index">Cart</a>
                            </li>
                        }
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
        <br />

    <br />

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FPTBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
<footer id="footer">
    <div class="container">
        <div class="row">

            <div class="col-md-4">

                <div class="footer-item">
                    <div class="company-brand">
                        <img src="images/main-logo.png" alt="logo" class="footer-logo">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis sed ptibus liberolectus nonet psryroin. Amet sed lorem posuere sit iaculis amet, ac urna. Adipiscing fames semper erat ac in suspendisse iaculis.</p>
                    </div>
                </div>

            </div>

            <div class="col-md-2">

                <div class="footer-menu">
                    <h5>About Us</h5>
                    <ul class="menu-list">
                        <li class="menu-item">
                            <a href="#">vision</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">articles </a>
                        </li>
                        <li class="menu-item">
                            <a href="#">careers</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">service terms</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">donate</a>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="col-md-2">

                <div class="footer-menu">
                    <h5>Discover</h5>
                    <ul class="menu-list">
                        <li class="menu-item">
                            <a href="#">Home</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Books</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Authors</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Subjects</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Advanced Search</a>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="col-md-2">

                <div class="footer-menu">
                    <h5>My account</h5>
                    <ul class="menu-list">
                        <li class="menu-item">
                            <a href="#">Sign In</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">View Cart</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">My Wishtlist</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Track My Order</a>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="col-md-2">

                <div class="footer-menu">
                    <h5>Help</h5>
                    <ul class="menu-list">
                        <li class="menu-item">
                            <a href="#">Help center</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Report a problem</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Suggesting edits</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Contact us</a>
                        </li>
                    </ul>
                </div>

            </div>

        </div>
        <!-- / row -->

    </div>
</footer>
</html>